// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Foreground","status":true,"description":"マップに合わせてスクロールする近景の設定(Ver1.1)","parameters":{}},
{"name":"Chronus","status":false,"description":"ゲーム内時間の導入プラグイン","parameters":{"月ごとの日数配列":"31,28,31,30,31,30,31,31,30,31,30,31","月名配列":"Jan.,Feb.,Mar.,Apr.,May.,Jun.,Jul.,Aug.,Sep.,Oct.,Nov.,Dec.","曜日配列":"(日),(月),(火),(水),(木),(金),(土)","自然時間加算":"5","自然時間加算間隔":"60","場所移動時間加算":"30","戦闘時間加算(固定)":"30","戦闘時間加算(ターン)":"5","年のゲーム変数":"0","月のゲーム変数":"0","日のゲーム変数":"0","曜日IDのゲーム変数":"0","曜日名のゲーム変数":"0","時のゲーム変数":"0","分のゲーム変数":"0","累計時間のゲーム変数":"0","累計日数のゲーム変数":"0","時間帯IDのゲーム変数":"0","天候IDのゲーム変数":"0","フォーマット時間の変数":"0","フォーマット時間の計算式":"HH24 * 60 + MI","日時フォーマット1":"YYYY年 MM月 DD日 DY","日時フォーマット2":"AMHH時 MI分","カレンダー表示X座標":"0","カレンダー表示Y座標":"0","カレンダーフォントサイズ":"0","カレンダー不透明度":"192","カレンダー余白":"8","文字盤画像ファイル":"","長針画像ファイル":"","短針画像ファイル":"","時計X座標":"84","時計Y座標":"156","イベント中時間経過":"false"}},
{"name":"HPConsumeSkill","status":false,"description":"HP消費技","parameters":{"Consume HP Color":"17"}},
{"name":"Yami_8DirEx","status":true,"description":"8方向移動(タッチパネル対応版)","parameters":{"dir4 Switch ID":"100"}},
{"name":"WeatherOnBattle","status":true,"description":"戦闘中も天候アニメを表示します","parameters":{}},
{"name":"SubMembersAttendBattle","status":false,"description":"同行者(NPC)を戦闘に参加させ、自動戦闘を行わせます","parameters":{"subMemberIdVal1":"1","subMemberIdVal2":"2","subMemberIdVal3":"3","subMemberIdVal4":"4"}},
{"name":"SimpleMsgSideViewMZ","status":true,"description":"サイドビューバトルでスキル/アイテムの名前のみ表示します。","parameters":{"displayAttack":"false","displayIcon":"true"}},
{"name":"TPB_Extension","status":true,"description":"TPB戦闘拡張プラグイン v1.0.1","parameters":{"FastForwardSpeed":"2","FastForwardAnimation":"false","OpenActorCommandSeFileName":"Flash2","OpenActorCommandSeVolume":"90","OpenActorCommandSePitch":"150","OpenActorCommandSePan":"0","WaitSkillOrItemWindow":"true","WaitPartyWindow":"true","FixedStatusWindow":"true"}},
{"name":"ChangeEquipOnBattleMZ","status":true,"description":"戦闘コマンドに装備変更を追加","parameters":{"commandName":"装備変更"}},
{"name":"AddAutoToActorCommand","status":true,"description":"戦闘のアクターコマンドの先頭か後尾に「オート」を追加します","parameters":{"commandName":"おまかせ","autoCommandPos":"0"}},
{"name":"BattleVoiceMZ","status":false,"description":"アクターの戦闘時の行動にボイスSEを設定します。","parameters":{"ON switch ID":"1002","volume":"90","pitch":"100","pan":"0","Battle Voice Name at Option":"バトルボイス"}},
{"name":"CommonEventStepRegion","status":true,"description":"タイルを踏んだ時、リージョンIDに応じてコモンイベントを起動","parameters":{}},
{"name":"wasdKeyMZ","status":true,"description":"wasd移動に対応させます。","parameters":{}},
{"name":"MenuSubMembersMZ","status":true,"description":"メニュー画面と隊列の最後尾に同行者を表示します","parameters":{"subMemberIdVal1":"13","subMemberIdVal2":"0","subMemberIdVal3":"0","subMemberIdVal4":"0","subMemberText":"同行者","displayIfNone":"false","subMemberNoneText":"なし","DisplayOnMap":"true","additionalFollower":"5"}}
];
